// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from "@hotwired/stimulus"
// import { application } from "./application"

// import { definitionsFromContext } from "stimulus/webpack-helpers"

const application = Application.start()

// const context = require.context("../controllers", true, /\.js$/)
// application.load(definitionsFromContext(context))

import HelloController from "./workout_controller.js"
application.register("workout", HelloController)
