# fly.toml app configuration file generated for sp-fitness on 2023-05-11T01:23:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sp-fitness"
primary_region = "eze"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
