default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  # reaping_frequency: nil
  timeout: 5000
  username: <%= `whoami`.chomp %>

development:
  <<: *default
  database: routines_development
  # host: localhost # Heroku
  host:     "/tmp/"              # works
  # socket: "/tmp/.s.PGSQL.5432" # does not work
  # socket: "/tmp/"              # does not work

test:
  <<: *default
  database: routines_test

production:
  <<: *default
  database: routines_production
  username: postgres
